import { createApp } from "vue";
import { createPinia } from "pinia";
import "./style.css";
import App from "./App.vue";
import router from "./router/index.js";
import Error from "@/components/Error.vue";
import Spin from "@/components/Spin.vue";
import SelectFilter from "@/components/SelectFilter.vue";
const pinia = createPinia();
const app = createApp(App);
app.use(router);
app.use(pinia);
app.component("Error", Error);
app.component("Spin", Spin);
app.component("SelectFilter", SelectFilter);
app.mount("#app");
